language: php
php:
  #- 5.5
  - 5.6
  #- 7.0
  #- hhvm

git:
  depth: 3

before_install:
  - composer self-update
  - composer --version

install:
  - composer install

before_script:
  - ./bin/suggest --env > .env

script:
  - composer test
  - ./bin/suggest --dry LACE

after_script:
  - cat .env

#End.
