language: php
php:
  - 7.0
  - 5.6
  #- hhvm

git:
  depth: 5

before_install:
  - composer self-update
  - composer --version

install:
  - composer install

before_script:
  - ./bin/suggest --env > .env

script:
  - composer test
  - ./bin/suggest --dry LACE

after_script:
  - cat .env
  - make --version
  - "printf node: && node --version"
  - "printf npm: && npm --version"
  - mvn --version

#End.
